### PR TITLE
Feature/wall nms

### PR DESCRIPTION
**Pull request by neethu-ms**
Wall component and config changes

### CODE REVIEW

**Comment by Dubi911** [comment]
Is it possible to change Port:8000 since you changed it to 3003?

**Comment by Dubi911** [comment]
When I try to run your branch 

```
Failed to compile.

./src/index.js
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/lighthouse/indezone-app/client/src'
```
**Solution**: Delete import statement line 5 of index.js

**Comment by Dubi911** [comment]
Also I can see that we are going to have a problem with `useApplicationData.js `mine works already so we should use mine, because yours gave a unfulfilled promise error.

**Solution: Empty or revert useApplicationData.js before merge**

**Comment by Dubi911** [comment]
Would like to know what npm package moment does

**Comment by altairioffe** [comment]
> **Add comment**
> Would like to know what npm package moment does

Moment is a library for working with time & dates.

**Pull request closed without merging**
